export const CATAGORIES_ACTION_TYPES={
FETCH_CATAGORIES_START:"category/FETCH_CATAGORIES_START",
FETCH_CATAGORIES_SUCCESS:"category/FETCH_CATAGORIES_SUCCESS",
FETCH_CATAGORIES_FAILED:"category/FETCH_CATAGORIES_FAILED"
}